version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bitsniff_db
    environment:
      POSTGRES_USER: bitsniff
      POSTGRES_PASSWORD: bitsniff19920622
      POSTGRES_DB: bitsniff
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitsniff"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 