-- AlterTable
ALTER TABLE "ethereum_transactions" ALTER COLUMN "value" SET DATA TYPE DECIMAL(78,18),
ALTER COLUMN "gasFee" SET DATA TYPE DECIMAL(78,18),
ALTER COLUMN "gasPrice" SET DATA TYPE DECIMAL(78,18);
